name = "medium-backend"
main = "src/index.ts"
compatibility_date = "2025-01-05"

# Environment variables
[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZWE2YjliMDctOGZmYS00NzY2LWE0NTgtYzQ1OTdlMDRkNDliIiwidGVuYW50X2lkIjoiMmVkOTlkNjA3MmM2MTE0OWFkMGM3YTA5NzkwMWQ3MDhjYzdiMzZmNWUxNzk4NmIzMDQxOWQwZGJkYzM2NGZjZSIsImludGVybmFsX3NlY3JldCI6IjcxZDM0NmM4LWQ3NTQtNDQ4Yi1hYTdmLWU3MDc4YjYwNDcxZSJ9.gAtRGaZNbCh8QcC5NWOP-wEA4tVLpyHoXdiD4ly0NaQ"
CLOUDINARY_CLOUD_NAME ="dwonmb0pm"
CLOUDINARY_API_KEY ="899476114153331"   
CLOUDINARY_API_SECRET="-QQGi32x_xIkE5AhaR2agrK0Xes"
